/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.sse.ustc.contract;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EnvironmentContract implements org.apache.thrift.TBase<EnvironmentContract, EnvironmentContract._Fields>, java.io.Serializable, Cloneable, Comparable<EnvironmentContract> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EnvironmentContract");

  private static final org.apache.thrift.protocol.TField ENVIRONMENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("environmentId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ENVIRONMENT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("environmentName", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EnvironmentContractStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EnvironmentContractTupleSchemeFactory());
  }

  public int environmentId; // required
  public String environmentName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ENVIRONMENT_ID((short)1, "environmentId"),
    ENVIRONMENT_NAME((short)2, "environmentName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ENVIRONMENT_ID
          return ENVIRONMENT_ID;
        case 2: // ENVIRONMENT_NAME
          return ENVIRONMENT_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ENVIRONMENTID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENVIRONMENT_ID, new org.apache.thrift.meta_data.FieldMetaData("environmentId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ENVIRONMENT_NAME, new org.apache.thrift.meta_data.FieldMetaData("environmentName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EnvironmentContract.class, metaDataMap);
  }

  public EnvironmentContract() {
  }

  public EnvironmentContract(
    int environmentId,
    String environmentName)
  {
    this();
    this.environmentId = environmentId;
    setEnvironmentIdIsSet(true);
    this.environmentName = environmentName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EnvironmentContract(EnvironmentContract other) {
    __isset_bitfield = other.__isset_bitfield;
    this.environmentId = other.environmentId;
    if (other.isSetEnvironmentName()) {
      this.environmentName = other.environmentName;
    }
  }

  public EnvironmentContract deepCopy() {
    return new EnvironmentContract(this);
  }

  @Override
  public void clear() {
    setEnvironmentIdIsSet(false);
    this.environmentId = 0;
    this.environmentName = null;
  }

  public int getEnvironmentId() {
    return this.environmentId;
  }

  public EnvironmentContract setEnvironmentId(int environmentId) {
    this.environmentId = environmentId;
    setEnvironmentIdIsSet(true);
    return this;
  }

  public void unsetEnvironmentId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENVIRONMENTID_ISSET_ID);
  }

  /** Returns true if field environmentId is set (has been assigned a value) and false otherwise */
  public boolean isSetEnvironmentId() {
    return EncodingUtils.testBit(__isset_bitfield, __ENVIRONMENTID_ISSET_ID);
  }

  public void setEnvironmentIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENVIRONMENTID_ISSET_ID, value);
  }

  public String getEnvironmentName() {
    return this.environmentName;
  }

  public EnvironmentContract setEnvironmentName(String environmentName) {
    this.environmentName = environmentName;
    return this;
  }

  public void unsetEnvironmentName() {
    this.environmentName = null;
  }

  /** Returns true if field environmentName is set (has been assigned a value) and false otherwise */
  public boolean isSetEnvironmentName() {
    return this.environmentName != null;
  }

  public void setEnvironmentNameIsSet(boolean value) {
    if (!value) {
      this.environmentName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ENVIRONMENT_ID:
      if (value == null) {
        unsetEnvironmentId();
      } else {
        setEnvironmentId((Integer)value);
      }
      break;

    case ENVIRONMENT_NAME:
      if (value == null) {
        unsetEnvironmentName();
      } else {
        setEnvironmentName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ENVIRONMENT_ID:
      return Integer.valueOf(getEnvironmentId());

    case ENVIRONMENT_NAME:
      return getEnvironmentName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ENVIRONMENT_ID:
      return isSetEnvironmentId();
    case ENVIRONMENT_NAME:
      return isSetEnvironmentName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EnvironmentContract)
      return this.equals((EnvironmentContract)that);
    return false;
  }

  public boolean equals(EnvironmentContract that) {
    if (that == null)
      return false;

    boolean this_present_environmentId = true;
    boolean that_present_environmentId = true;
    if (this_present_environmentId || that_present_environmentId) {
      if (!(this_present_environmentId && that_present_environmentId))
        return false;
      if (this.environmentId != that.environmentId)
        return false;
    }

    boolean this_present_environmentName = true && this.isSetEnvironmentName();
    boolean that_present_environmentName = true && that.isSetEnvironmentName();
    if (this_present_environmentName || that_present_environmentName) {
      if (!(this_present_environmentName && that_present_environmentName))
        return false;
      if (!this.environmentName.equals(that.environmentName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(EnvironmentContract other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEnvironmentId()).compareTo(other.isSetEnvironmentId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnvironmentId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.environmentId, other.environmentId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnvironmentName()).compareTo(other.isSetEnvironmentName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnvironmentName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.environmentName, other.environmentName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EnvironmentContract(");
    boolean first = true;

    sb.append("environmentId:");
    sb.append(this.environmentId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("environmentName:");
    if (this.environmentName == null) {
      sb.append("null");
    } else {
      sb.append(this.environmentName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EnvironmentContractStandardSchemeFactory implements SchemeFactory {
    public EnvironmentContractStandardScheme getScheme() {
      return new EnvironmentContractStandardScheme();
    }
  }

  private static class EnvironmentContractStandardScheme extends StandardScheme<EnvironmentContract> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EnvironmentContract struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ENVIRONMENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.environmentId = iprot.readI32();
              struct.setEnvironmentIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ENVIRONMENT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.environmentName = iprot.readString();
              struct.setEnvironmentNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EnvironmentContract struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ENVIRONMENT_ID_FIELD_DESC);
      oprot.writeI32(struct.environmentId);
      oprot.writeFieldEnd();
      if (struct.environmentName != null) {
        oprot.writeFieldBegin(ENVIRONMENT_NAME_FIELD_DESC);
        oprot.writeString(struct.environmentName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EnvironmentContractTupleSchemeFactory implements SchemeFactory {
    public EnvironmentContractTupleScheme getScheme() {
      return new EnvironmentContractTupleScheme();
    }
  }

  private static class EnvironmentContractTupleScheme extends TupleScheme<EnvironmentContract> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EnvironmentContract struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEnvironmentId()) {
        optionals.set(0);
      }
      if (struct.isSetEnvironmentName()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetEnvironmentId()) {
        oprot.writeI32(struct.environmentId);
      }
      if (struct.isSetEnvironmentName()) {
        oprot.writeString(struct.environmentName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EnvironmentContract struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.environmentId = iprot.readI32();
        struct.setEnvironmentIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.environmentName = iprot.readString();
        struct.setEnvironmentNameIsSet(true);
      }
    }
  }

}

