/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.sse.ustc.contract;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MapFormat implements org.apache.thrift.TEnum {
  JPEG(1),
  BMP(2),
  GIF(3),
  PNG(4),
  PSD(5);

  private final int value;

  private MapFormat(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MapFormat findByValue(int value) { 
    switch (value) {
      case 1:
        return JPEG;
      case 2:
        return BMP;
      case 3:
        return GIF;
      case 4:
        return PNG;
      case 5:
        return PSD;
      default:
        return null;
    }
  }
}
