/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.sse.ustc.contract;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PathEdge implements org.apache.thrift.TBase<PathEdge, PathEdge._Fields>, java.io.Serializable, Cloneable, Comparable<PathEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PathEdge");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField VERTEX_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("vertexId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField NEIGHBOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("neighborId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PathEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PathEdgeTupleSchemeFactory());
  }

  public int id; // required
  public int vertexId; // required
  public int neighborId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    VERTEX_ID((short)2, "vertexId"),
    NEIGHBOR_ID((short)3, "neighborId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // VERTEX_ID
          return VERTEX_ID;
        case 3: // NEIGHBOR_ID
          return NEIGHBOR_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __VERTEXID_ISSET_ID = 1;
  private static final int __NEIGHBORID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.VERTEX_ID, new org.apache.thrift.meta_data.FieldMetaData("vertexId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NEIGHBOR_ID, new org.apache.thrift.meta_data.FieldMetaData("neighborId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PathEdge.class, metaDataMap);
  }

  public PathEdge() {
  }

  public PathEdge(
    int id,
    int vertexId,
    int neighborId)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.vertexId = vertexId;
    setVertexIdIsSet(true);
    this.neighborId = neighborId;
    setNeighborIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PathEdge(PathEdge other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.vertexId = other.vertexId;
    this.neighborId = other.neighborId;
  }

  public PathEdge deepCopy() {
    return new PathEdge(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setVertexIdIsSet(false);
    this.vertexId = 0;
    setNeighborIdIsSet(false);
    this.neighborId = 0;
  }

  public int getId() {
    return this.id;
  }

  public PathEdge setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getVertexId() {
    return this.vertexId;
  }

  public PathEdge setVertexId(int vertexId) {
    this.vertexId = vertexId;
    setVertexIdIsSet(true);
    return this;
  }

  public void unsetVertexId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VERTEXID_ISSET_ID);
  }

  /** Returns true if field vertexId is set (has been assigned a value) and false otherwise */
  public boolean isSetVertexId() {
    return EncodingUtils.testBit(__isset_bitfield, __VERTEXID_ISSET_ID);
  }

  public void setVertexIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VERTEXID_ISSET_ID, value);
  }

  public int getNeighborId() {
    return this.neighborId;
  }

  public PathEdge setNeighborId(int neighborId) {
    this.neighborId = neighborId;
    setNeighborIdIsSet(true);
    return this;
  }

  public void unsetNeighborId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NEIGHBORID_ISSET_ID);
  }

  /** Returns true if field neighborId is set (has been assigned a value) and false otherwise */
  public boolean isSetNeighborId() {
    return EncodingUtils.testBit(__isset_bitfield, __NEIGHBORID_ISSET_ID);
  }

  public void setNeighborIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NEIGHBORID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case VERTEX_ID:
      if (value == null) {
        unsetVertexId();
      } else {
        setVertexId((Integer)value);
      }
      break;

    case NEIGHBOR_ID:
      if (value == null) {
        unsetNeighborId();
      } else {
        setNeighborId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Integer.valueOf(getId());

    case VERTEX_ID:
      return Integer.valueOf(getVertexId());

    case NEIGHBOR_ID:
      return Integer.valueOf(getNeighborId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case VERTEX_ID:
      return isSetVertexId();
    case NEIGHBOR_ID:
      return isSetNeighborId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PathEdge)
      return this.equals((PathEdge)that);
    return false;
  }

  public boolean equals(PathEdge that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_vertexId = true;
    boolean that_present_vertexId = true;
    if (this_present_vertexId || that_present_vertexId) {
      if (!(this_present_vertexId && that_present_vertexId))
        return false;
      if (this.vertexId != that.vertexId)
        return false;
    }

    boolean this_present_neighborId = true;
    boolean that_present_neighborId = true;
    if (this_present_neighborId || that_present_neighborId) {
      if (!(this_present_neighborId && that_present_neighborId))
        return false;
      if (this.neighborId != that.neighborId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(PathEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVertexId()).compareTo(other.isSetVertexId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVertexId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vertexId, other.vertexId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNeighborId()).compareTo(other.isSetNeighborId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNeighborId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.neighborId, other.neighborId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PathEdge(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("vertexId:");
    sb.append(this.vertexId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("neighborId:");
    sb.append(this.neighborId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PathEdgeStandardSchemeFactory implements SchemeFactory {
    public PathEdgeStandardScheme getScheme() {
      return new PathEdgeStandardScheme();
    }
  }

  private static class PathEdgeStandardScheme extends StandardScheme<PathEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PathEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VERTEX_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.vertexId = iprot.readI32();
              struct.setVertexIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NEIGHBOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.neighborId = iprot.readI32();
              struct.setNeighborIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PathEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(VERTEX_ID_FIELD_DESC);
      oprot.writeI32(struct.vertexId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NEIGHBOR_ID_FIELD_DESC);
      oprot.writeI32(struct.neighborId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PathEdgeTupleSchemeFactory implements SchemeFactory {
    public PathEdgeTupleScheme getScheme() {
      return new PathEdgeTupleScheme();
    }
  }

  private static class PathEdgeTupleScheme extends TupleScheme<PathEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PathEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetVertexId()) {
        optionals.set(1);
      }
      if (struct.isSetNeighborId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetVertexId()) {
        oprot.writeI32(struct.vertexId);
      }
      if (struct.isSetNeighborId()) {
        oprot.writeI32(struct.neighborId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PathEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.vertexId = iprot.readI32();
        struct.setVertexIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.neighborId = iprot.readI32();
        struct.setNeighborIdIsSet(true);
      }
    }
  }

}

