/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.sse.ustc.contract;

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TagType implements org.apache.thrift.TEnum
{
    WIFI(1), MOBILEPHONE(2), LAPTOP(3), PAD(4), RFID(5), STA(6);

    private final int value;

    private TagType(int value)
    {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue()
    {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * 
     * @return null if the value is not found.
     */
    public static TagType findByValue(int value)
    {
        switch (value)
        {
            case 1:
                return WIFI;
            case 2:
                return MOBILEPHONE;
            case 3:
                return LAPTOP;
            case 4:
                return PAD;
            case 5:
                return RFID;
            case 6:
                return STA;
            default:
                return null;
        }
    }
}
